name: Build Docker Image

on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
        - "4"
        - "4/fastcgi"
    steps:
    - uses: actions/checkout@v1
    - name: docker build
      id: build
      run: |
        printf "::group::Sending context\n"
        IMAGE=adminer:${VARIANT/\//-}-$(date +%s)
        docker build "$VARIANT" --tag "$IMAGE" |sed 's/^Step/::endgroup::\n::group::Step/'
        printf "::endgroup::\n"
        printf "::set-output name=%s::%s\n" "image" "$IMAGE"
      env:
        VARIANT: ${{ matrix.variant }}
    - run: docker run --name adminer -d ${{ steps.build.outputs.image }}
    - run: docker ps -a
